version: '3.7'
services:
    board:
        container_name: baord
        image: mysql:5.7.27
        restart: always
        environment: 
          - MYSQL_USER=board
          - MYSQL_PASSWORD=password
          - MYSQL_ROOT_PASSWORD=password
          - MYSQL_DATABASE=board
          - TZ=Asia/Seoul
        ports:
          - '3308:3306'
        command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
