service:
  name: board
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# Add the serverless-webpack plugin
plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    SLS_DEBUG: true

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          method: get
          path: hello
